CREATE TABLE IF NOT EXISTS members
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(50)  NOT NULL UNIQUE,
    password           VARCHAR(255) NOT NULL,
    role               VARCHAR(20)  NOT NULL,
    created_date       TIMESTAMP,
    last_modified_date TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contents
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(100) NOT NULL,
    description        TEXT,
    view_count         BIGINT       NOT NULL DEFAULT 0,
    created_by         VARCHAR(50)  NOT NULL,
    last_modified_by   VARCHAR(50),
    created_date       TIMESTAMP,
    last_modified_date TIMESTAMP
);
